### ISSUE TITLE
Add page for members of drek + their emails

### ISSUE THREAD

**Issue by Herkarl** [datasektionen/bawang-content#181]
D-rek saknar sida där alla som för närvarande sitter i den står + deras mailaddresser, tycker det känns ganska rimligt att lägga till en sån.

de sidor som finns är [datasektionen.se/organisation/sammansattning](https://datasektionen.se/organisation/sammansattning), där inga mail står med, och [datasektionen.se/kontakt#styrelsen](https://datasektionen.se/kontakt#styrelsen), där bara ordf står (utöver mailen som går till hela styrelsen). Tycker nog inte det borde stå på första. Kanske att man vill lägga det på den andra sidan? Men är också nice att den är så koncis. 

Potentiellt så vill man kanske skapa en helt ny sida för styrelsen, men osäker på vilken kategori den borde hamna i. Nämnder är typ bäst, men styrelsen är tekniskt sett inte en nämnd.

**Comment by triggerdude33** [comment]
Ett förslag är att döpa om "organisation > D-rektoratets sammansättning" till "organisation > D-rektoratet". Sen på den sidan har man både information om sammansättningen, samt vilka som besitter posterna just nu. Typ så här:

**NUVARANDE SAMMANSÄTTNING**

**Post 1**
bildpåperson1
namn1
mail1

**Post 2**
bildpåperson2
namn2
mail2

...

**SAMMANSÄTTNING**

...

**Comment by Herkarl** [comment]
Fixed in #223

**Comment by Herkarl** [comment]
Tycker dock fortfarande det vore ganska bra om man kunde se vilka som för närvarande sitter på posterna, så öppnar den här igen.
