### ISSUE TITLE
Broken links

### ISSUE THREAD

**Issue by addem1234** [datasektionen/bawang-content#27]
~https://datasektionen.se/organisation
broken: https://datasektionen.se/sektionen/formalia/verksamhetsplan
broken: https://datasektionen.se/sektionen/formalia/budget~

~https://datasektionen.se/sektionen/lokalbokning
broken: http://datasektionen.se/sektionen/organisation/samboendeavtal.pdf~

~https://datasektionen.se/namnder/prylmangleriet
broken: http://www.datasektionen.se/sektionen/namnder/prylis/trojor~

~https://datasektionen.se/namnder/tag-monkeys
broken: https://datasektionen.se/namnder/ior~

~https://datasektionen.se/namnder
broken: https://datasektionen.se/namnder/naringslivsgruppen
broken: https://datasektionen.se/studier/studienamnden~

https://datasektionen.se/namnder/qulturnamnden
broken: http://www.datasektionen.se/sektionen/qn/motesprotokoll
- This one is also lost.

**Comment by karlek** [comment]
Anyone got the PDF?

**Comment by Plongy** [comment]
What PDF?

**Comment by karlek** [comment]
Samboendeavtal.pdf

**Comment by karlek** [comment]
damn you're fast

**Comment by Plongy** [comment]
When budgetuppföljing after 12, everything's an excuse

**Comment by karlek** [comment]
Is it one of these: 
```
[Samboavtalet 2015](https://static.datasektionen.se/organisation/samboendeavtal.pdf)
[Samboavtalet 2016](https://static.datasektionen.se/organisation/samboendeavtal_2016.pdf)
```
?

**Comment by Plongy** [comment]
Damn, just found it

**Comment by Plongy** [comment]
Second one

**Comment by karlek** [comment]
Cool

**Comment by Plongy** [comment]
(Just by guessing paths though :P )

**Comment by karlek** [comment]
Ty @Plongy <3

**Comment by karlek** [comment]
Apparently NLG has no nämndpage describing it's activities. Something the you guys want? @albinso

**Comment by Fexlom** [comment]
NLG has a top-level page at [/naringsliv](https://datasektionen.se/naringsliv) instead, but maybe we want a committee page too? I'll ping the NLA.
