### ISSUE TITLE
Ordnar

### ISSUE THREAD

**Issue by Plongy** [datasektionen/bawang-content#28]
Den här sidan tycks ha försvunnit i flytten... högst pinigt: https://purjo.datasektionen.se/sektionen/ordnar

**Comment by karlek** [comment]
I just copied the old information from purjo, but don't we have "kassörorden" now as well? Then someone probably needs to do some digging for old names!

**Comment by karlek** [comment]
Also new names need to be added for this year!

**Comment by Plongy** [comment]
Kassörsordern doesn't really have any members yet, but i have a list of all it's future members :)

**Comment by Plongy** [comment]
But new names have been added
