### ISSUE TITLE
Broken links

### ISSUE THREAD

**Issue by Adasjo** [datasektionen/bawang-content#373]
We have broken links all over our website.

**Comment by Adasjo** [comment]
https://datasektionen.se/studier

- Studenträtt
- [EECS-kansliet och studievägledning](https://www.kth.se/student/studievagledning-kontakt/kontakt-studievagledning-pa-program-1.84623)
- [Studievägledningen](https://www.kth.se/student/studievagledning-kontakt)
- [Utbytesstudier](https://www.kth.se/student/program/utlandsstudier/utbyte?programme=d)
- [FAQ från THS](http://ths.kth.se/contact/faq/education-and-studysocial)
For example

**Comment by Grunler** [comment]
I'll try to fix the ones listed here today.
