### ISSUE TITLE
Missing files crashes website?

### ISSUE THREAD

**Issue by pnyberg** [datasektionen/bawang-content#49]
Apparently if you create a namnd-folder but doesn't put in all the necessary files (sidebary.md, body.md and meta.toml) you crash the whole site. This is probably bad?

**Comment by addem1234** [comment]
Possibly fixed by [this taitan commit](https://github.com/datasektionen/taitan/commit/486204b2707bde67fb0b43997e1c5a99f695ebb6)

**Comment by karlek** [comment]
Is this still a problem @addem1234?

**Comment by addem1234** [comment]
I think I reopened because I didn't test it, but it should be fine 😅

**Comment by karlek** [comment]
Haha, okey. I'll close this issue then, better to create a new one if the problem persists :)
