### ISSUE TITLE
Skriv om FAQ

### ISSUE THREAD

**Issue by Benjaneb** [datasektionen/bawang-content#502]
Den nuvarande [FAQ-sidan](https://github.com/datasektionen/bawang-content/blob/master/sektionen/faq/body.md) svarar på frågor om hur man arrangerar event som funktionär. Det är inte vad den genomsnittliga besökaren av vår hemsida vill veta om sektionen. FAQ borde istället svara på generella frågor som folk som inte vet något om sektionen kan vilja veta. T.ex vad en nämnd är, vad en funktionär är och hur man kan börja engagera sig i sektionen.

**Comment by Herkarl** [comment]
Kanske rimligt att döpa om FAQn till något mer representativt av innehållet och skapa en ny FAQ-sida? För innehållet på nuvarande FAQ-sidan är  ju inte direkt orimligt/felaktigt, så kan vara bra att ha

**Comment by Benjaneb** [comment]
Egentligen vill vi ju se till att det inte finns för mycket delsidor så det kanske vore rimligt att förvänta sig att funktionärer lär sig om det där på andra platser än att läsa på vår hemsida, som funktionärsguide-dokument. Skulle själv tycka att man vill prioritera innehållet på hemsidan till gemene sektionsmedlem och lite externa människor.

**Comment by Benjaneb** [comment]
Den objektiva åsikten av Dogge är att lägga till det innehållet som faktiskt är korrekt i bra-att-ha-saker-mappen i Drive och sen skriva om FAQ:n med det jag nämnde.

**Comment by Benjaneb** [comment]
Fixat i #531
