### ISSUE TITLE
Skriv om dokumentation om mörkläggning

### ISSUE THREAD

**Issue by foodelevator** [datasektionen/bawang-content#516]
Alltså detta: https://github.com/datasektionen/bawang-content/blob/3f717fcf979b2234af8e8a6f1e04dcbf7e534916/README.md?plain=1#L32-L35

Kanske bara länka till <https://github.com/datasektionen/taitan/tree/ccd5a242493b8b6afb81ce73244be05f3ee63d89?tab=readme-ov-file#darkmode-hiding-info-during-reception>, så det inte finns risk att det som står i det här repot blir gammalt.
Men det bör också framgå tydligt att det går att sätta `Sensitive`-flaggan i `meta.toml` så det kanske är värt att skriva om de två sakerna på ett ställe ändå.

**Comment by Herkarl** [comment]
Tänkte när jag skrev om readmen i taitan att det nog är bäst att skriva allt i bawang-content också, mest för att det blir mer lättillgängligt då, men är visserligen sant att det lättare blir utdaterat då.

**Comment by mathiasmagnusson** [comment]
Jo men kom på sen att det borde stå om både `{{ if .reception }}` och `Sensitive = true` på ett och samma ställe och det kan typ lika gärna vara här ändå. (I formen av typ "hur man gör med content som ska mörkläggas. Är nog rätt lätt hänt att man missar att `Sensitive`-fältet finns om man endast länkar till den jag länkade till ovan)

**Comment by foodelevator** [comment]
Closed by  #521
