### ISSUE TITLE
Fel ordförande! Vafan skärp er.

### ISSUE THREAD

**Issue by HerrLantz** [datasektionen/bawang-content#59]
# Hur fan kan ni fucka upp så här mycket!?
<img width="210" alt="image" src="https://user-images.githubusercontent.com/7319117/35220452-bfd94b02-ff76-11e7-9a8a-7367ecdfcf44.png">
https://datasektionen.se/kontakt #58

**Comment by Plongy** [comment]
I approve :+1:
