### ISSUE TITLE
Site looks bad on mobile

### ISSUE THREAD

**Issue by LudwikJaniuk** [datasektionen/bawang-content#8]
Here are some screenshots:

First impression:
![First impression](https://cloud.githubusercontent.com/assets/6298393/15388683/6705585a-1db3-11e6-9a02-f5fc6b1286ce.png)

![screenshot_2016-05-19-11-09-59](https://cloud.githubusercontent.com/assets/6298393/15388657/47e8eba8-1db3-11e6-895b-9228d8bbc15d.png)
Man kanske skulle zooma ut?
![screenshot_2016-05-19-11-10-29](https://cloud.githubusercontent.com/assets/6298393/15388660/47ebe57e-1db3-11e6-86f5-1047b3911f30.png)
![screenshot_2016-05-19-11-10-13](https://cloud.githubusercontent.com/assets/6298393/15388656/47e8b372-1db3-11e6-998e-3a74e30f4978.png)
![screenshot_2016-05-19-11-10-05](https://cloud.githubusercontent.com/assets/6298393/15388658/47e94198-1db3-11e6-8b3a-7ec0f4bdebf5.png)

**Comment by macfeaster** [comment]
Tack för uppmärksammandet! Det här är issues som rör mallen för datasektionen.se och bör därför rapporteras i repot gloo-bawang.
